### PR TITLE
Removed unwanted strikethrough effect from Select

### PR DESCRIPTION
**Pull request by vfproductions**
Select doesn't reserve enough space for the label unless you specify the label prop

image

### CODE REVIEW

**Comment by Zenoo** [comment]
Indeed, nice catch.  
Why did you rename `defaultThemes.ts` though?

**Comment by vfproductions** [comment]
It was a while ago, sorry, but I think it was a lint error.   Maybe a windows/linux thing?  I'm on windows

If you look here its referenced as DefaultThemes
https://github.com/Zenoo/mui-theme-creator/blob/master/src/components/SavedThemes/DefaultThemesComponent.tsx#L6

Another thing I had to change (but did not add to PR) was removing the word "bash" from the yarn deploy command.   Not sure if that's helpful or hurtful to anyone else.   But after that I was able to build/deploy my fork

**Comment by Zenoo** [comment]
It would be better to change the import statement than to rename the file itself then, it's less likely to break things down the line that way.

**Comment by vfproductions** [comment]
I reverted it and I could still build.   Must be an "intellisense only" error in VS Code.   But not relevant to this PR so someone else can fix those later if needed.

**Comment by Zenoo** [comment]
Thanks for your contribution !

**Pull request merged**
